* Author: Biju Das
* Date Created: 15 June 2016
* Environment
  - OS: Windows 7,Ubuntu-16.04,CentOS-6
  - Browsers: Firefox-42.0,Chrome-47.0,Chromium-45.0
  - Bandwidth : 100Mbps
  - Hardware Configuration:8GB RAM  
  - Processor:i7,
  
* Objective
  - To view the Experiment of the Harmonically Excited Support Motion of a  Single DOF System experiment
  
* Pre conditions
  1. Open the url vlabs.ac.in and vlabs home page will be displayed 
  2. Click on IIT-Guwahati and a list of labs will be displayed on the screen 
  3. Select Mechanical Vibration Lab, a home page will be displayed and click on List of experiments link, where a list of experiments will be displayed on the screen
  4. Select "Harmonically Excited Support Motion of a  Single DOF System" experiment.

* Post conditions
   - Nil

* Test Steps
  1. Click on the Experiment link 
  2. Click on the link "Download Executable File to perform later( Low Bandwidth)"
  3. Run the exe file present in the zip folder.

* Expected result
  1. Experiment page should be opened
  2. The zip file should get downloaded in the system. Extract the zip file after it is downloaded.
  3. The experiment should run properly.

* Review comments
